// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyddakfwhxjdkbbnjpha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZGRha2Z3aHhqZGtiYm5qcGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NTY0NDAsImV4cCI6MjA1NjIzMjQ0MH0.MfXQ5q4imGKsUdw0MO9rQuDOMWFskO3RVwSgxz5LjTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);